### ISSUE TITLE
different version

### ISSUE THREAD

**Issue by diomed** [mburakerman/vuexplosive-modal#1]
hello

would you maybe be interested in making different version of a modal?

**Comment by mburakerman** [comment]
Hello.

How different? Could you be more specific?

**Comment by diomed** [comment]
one that would expand [like this](https://codyhouse.co/demo/animated-sign-up-flow/index.html)

**Comment by mburakerman** [comment]
Actually i wanted to make this so simple but you can take the code and customize as you like.
